---
include:
  - board: nice_nano
    shield: hurna
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano
    shield: hurna_dongle dongle_display
  - board: nice_nano
    shield: settings_reset
